# 
#
name: Website Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    needs: type-check

    steps:
      - uses: actions/checkout@v4

      - name: 'Install Node.js 22'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
